### ISSUE TITLE
The code does not work for ICML. 

### ISSUE THREAD

**Issue by tieqiao** [pranftw/openreview_scraper#2]
https://openreview.net/group?id=ICML.cc/2023/Conference

The code does not work for ICML.

**Comment by pranftw** [comment]
Hey @tieqiao, thanks for the issue. I checked the ICML 2023 page on OpenReview and it seems that ICML hasn't yet released the reviews yet. This code only works after the reviews are made publicly available. Hope you understand! Thanks for trying out the repo and be sure to check back once the reviews are released! Cheers!
